### ISSUE TITLE
Webexample/pom.skeleton.xml: No such file or directory

### ISSUE THREAD

**Issue by samizel** [darugnaa/deployment-package-example#1]
Hey,

I'm looking for a way to build .dp Files in an automated fashion to include this in a build-pipeline. I want to do this to create Kura Packages.
Your repository addresses this problem but doesn't work right now.

"$ ./setup-pom.sh
I will download the Kura workspace archive
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31.1M  100 31.1M    0     0  4415k      0  0:00:07  0:00:07 --:--:-- 5751k
Uncompressing Kura workspace archive
cat: org.darugna.alessandro.webexample/pom.skeleton.xml: No such file or directory
pom.xml ready."

Additionally I would like to ask if there is maybe a better way to create my desired deployment packages.

Greetings
samizel

**Comment by darugnaa** [comment]
Hi, I am not aware of a better way to create DPs. I will check my scripts this weekend and fix the problem you encounter while building the example.
Thanks for opening this issue

**Comment by darugnaa** [comment]
I updated the setup script, forgot an unnecessary operation.
Unfortunately I'm using an old version of Kura and Maven will later complain abou API jar missing, I'll try to update to the last 3.1.0.
Anyway, the DP packaging work is done by **distrib** project, just copy and adapt it within your projects
